### ISSUE TITLE
echo Output special characters

### ISSUE THREAD

**Issue by zhongjixiuxing** [stanislav-web/phalcon-uploader#6]
Hi phalcon-uploader author :
    i download this tool to use, is can't working. and then, i find in front of a blank line has one special character, i delete this blank line and it is working.... but , in browser is show some special characters, what is happen in phalcon-uploader? how to solve it ?

**Comment by zhongjixiuxing** [comment]
follow  is some special characters info in bowser:

![image](https://cloud.githubusercontent.com/assets/8935235/8591467/169882f2-265b-11e5-8974-96dacd869052.png)

**Comment by stanislav-web** [comment]
Hello, i was fixed it! Thank you!
